language: node_js
node_js:
- 0.1
before_install: npm install -g bower grunt-cli
install: npm install
before_script: bower install
deploy:
  provider: openshift
  user: mediamatik@seco.admin.ch
  password:
    secure: dC1fXoWSaiF8ossjbRHkCWfJtm/B44f0y48HjXoGj8jF+7TtQ42WsA1McKOC6ngx/EuO6fxp90OincdjGMzLX1Fh+yVEYn2IRiGP4i+ErK/SLuSnbz8y21t+sIsOFt6f8PvHbISNcON5eGDDRmecDFLyE5b1m66+oVMm7W4UxuE=
  app: ng
  domain: alvch
  on:
    repo: tdascoli/alv-ch-ng.demo
