language: node_js
node_js:
- 0.1
before_install: npm install -g bower grunt-cli
install: npm install
before_script: bower install
deploy:
  provider: openshift
  user: mediamatik@seco.admin.ch
  password:
    secure: OQ6zrlR+o8Ph3O16n8djb/mL6zXb1du6W5VizjE1cgcPcPykZoNloXEccqDfFAz0FLh9tCWQuvZfOd+4GXBOL7uVzdb7aQnAHfkItdOewFp1JfPZ73gX1KI7dX7okLWGi1uLgGXEzYeZNwMktvNheg5h2JJSwiErqjjAwX+0Q9E=
  app: ng
  domain: alvchegov
  on:
    repo: alv-ch-ng/demo
