language: node_js
node_js:
- 0.1
before_install: npm install -g bower grunt-cli
install: npm install
before_script: bower install
deploy:
  provider: openshift
  user: mediamatik@seco.admin.ch
  password:
    secure: UBzfcR82i73ODJJadK5WlqF1Phxkp/U4Neq1Tlz//gaSuRyH4h3XESren7mdVQ2lII2ADccW9MwvrErStdWHdsVymRXUxCf1foL8CvECBdfIPRf0VMF21VDTKVx91nJStfpt74H6lHejSiDWnvtLb+w9cdvx29J2z0JoWmo57qc=
  app: ngdemo
  domain: alvch
  on:
    repo: tdascoli/alv-ch-ng.demo
